name: 'spond_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'spond_analytics_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory to store compiled SQL files
clean-targets:         # directories to clean when `dbt clean` is run
  - "target"
  - "dbt_packages"

models:
  spond_analytics:
    # Default for all models in your project - usually 'view' or nothing set here
    # +materialized: view # You might see this commented out or not present

    staging:
      # This explicitly sets materialization for all models in the 'staging' folder
      +materialized: table # <--- CHANGE THIS LINE TO 'table'
    
    marts:
      # This explicitly sets materialization for all models in the 'marts' folder
      +materialized: table # This should already be 'table' or can be set to 'table'