# dbt/models/sources.yml
version: 2

sources:
  - name: public
    database: "{{ env_var('DBT_POSTGRES_DBNAME') }}"
    schema: public
    tables:
      - name: raw_teams
        identifier: teams
      - name: raw_memberships
        identifier: memberships
      - name: raw_events
        identifier: events
      - name: raw_event_rsvps # <--- What is the 'name' here?
        identifier: event_rsvps # <--- What is the 'identifier' here?