version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: spond-postgres
    environment:
      POSTGRES_DB: spond_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spond_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5

  ingester:
    build:
      # Change the context to the 'ingestion' directory
      context: ./ingestion # <--- CHANGE THIS LINE
      dockerfile: Dockerfile # <--- CHANGE THIS LINE (no longer needs ./ingestion/)
    container_name: spond-ingester
    depends_on:
      db:
        condition: service_healthy # Ensure DB is ready before ingester starts
    environment:
      DB_HOST: db # Hostname for services within Docker network
      DB_PORT: 5432
      DB_NAME: spond_analytics
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      # These paths are relative to the docker-compose.yml location (project root)
      # and map into the container's /app directory.
      - ./teams.csv:/app/teams.csv:ro
      - ./memberships.csv:/app/memberships.csv:ro
      - ./events.csv:/app/events.csv:ro
      - ./event_rsvps.csv:/app/event_rsvps.csv:ro
    command: python ingest_data.py # Command to run the ingestion script

  dbt-cli:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: spond-dbt-cli
    depends_on:
      db:
        condition: service_healthy # Ensure DB is ready for dbt
    environment:
      DBT_POSTGRES_HOST: db # Hostname for services within Docker network
      DBT_POSTGRES_PORT: 5432
      DBT_POSTGRES_USER: postgres
      DBT_POSTGRES_PASSWORD: postgres
      DBT_POSTGRES_DBNAME: spond_analytics
      DBT_POSTGRES_SCHEMA: public # Default schema for dbt to build into
    volumes:
      - ./dbt:/usr/app/dbt # Mount the dbt project into the container
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml:ro # Mount profiles.yml
    working_dir: /usr/app/dbt # Set working directory to the dbt project root
    entrypoint: dbt # Set dbt as the default command

volumes:
  postgres_data: