seeds:
  - name: country_codes
    description: "List of valid ISO 3166-1 country codes and associated data."
    columns:
      - name: name
        description: "The full country name."
        tests:
          - not_null
          - unique
      - name: alpha_two
        description: "The 2-letter Alpha-2 country code."
        tests:
          - not_null
          - unique
      - name: alpha_three
        description: "The 3-letter Alpha-3 country code. Used for filtering teams."
        tests:
          - not_null
          - unique
      - name: country_code
        description: "The numeric country code."
        tests:
          - not_null
          - unique
      - name: iso
        description: "ISO 3166-2 subdivision code (e.g., US-CA)."
        tests:
          - not_null
          - unique
      - name: region
        description: "Geographic region."
      - name: sub_region
        description: "Geographic sub-region."
      - name: intermediate_region
        description: "Geographic intermediate-region."
      - name: region_code
        description: "Numeric region code."
      - name: sub-region_code
        description: "Numeric sub-region code."
      - name: intermediate_region-code
        description: "Numeric intermediate-region code."