# dbt/models/staging/schema.yml

models:
  - name: event_rsvps
    description: Staging model for event RSVPs
    columns:
      - name: event_rsvp_id
        description: Primary key for event RSVPs.
        tests:
          - not_null
          - unique
      - name: event_id
        description: Foreign key to events.
        tests:
          - not_null
      - name: membership_id
        description: Foreign key to memberships.
        tests:
          - not_null:
              severity: warn
      - name: rsvp_status
        description: RSVP status (0, 1, 2).
        tests:
          - accepted_values:
              values: ['0', '1', '2']
      - name: responded_at
        description: Timestamp of when the RSVP was responded.