models:
  - name: event_rsvps
    description: Staging model for event RSVPs
    columns:
      - name: event_rsvp_id
        description: Primary key for event RSVPs.
        tests:
          - not_null
          - unique
      - name: event_id
        description: Foreign key to events.
        tests:
          - not_null
      - name: membership_id
        description: Foreign key to memberships.
        tests:
          - not_null:
              severity: warn
      - name: rsvp_status
        description: RSVP status (0, 1, 2).
        tests:
          - accepted_values:
              values: ['0', '1', '2']
      - name: responded_at
        description: Timestamp of when the RSVP was responded.
- name: teams
    description: Staging model for teams data, filtered for valid types and country codes.
    columns:
      - name: team_id
        description: Unique integer identifier for the team.
        tests:
          - not_null
          - unique
      - name: team_activity
        description: The primary activity of the team (string).
      - name: country_code
        description: Alpha-3 country code of the team's origin.
      - name: created_at
        description: UTC timestamp of when the team record was created (ISO 8601 format).